=== myasinay/cs50-idea-generator/static/docs/data.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "template": {
      "type": "array",
      "items": [
        {
          "type": "string"
        },
        {
          "type": "string"
        },
        {
          "type": "string"
        },
        {
          "type": "string"
        },
        {
          "type": "string"
        },
        {
          "type": "string"
        },
        {
          "type": "string"
        },
        {
          "type": "string"
        }
      ]
    },
    "genre": {
      "type": "array",
      "items": [
        {
          "type": "string"
        },
        {
          "type": "string"
        }
      ]
    },
    "genre_modifier": {
      "type": "array",
      "items": [
        {
          "type": "string"
        },
        {
          "type": "string"
        }
      ]
    },
    "perspective": {
      "type": "array",
      "items": [
        {
          "type": "string"
        },
        {
          "type": "string"
        }
      ]
    },
    "character": {
      "type": "object",
      "properties": {
        "nature": {
          "type": "array",
          "items": [
            {
              "type": "string"
            },
            {
              "type": "string"
            }
          ]
        },
        "description": {
          "type": "array",
          "items": [
            {
              "type": "string"
            },
            {
              "type": "string"
            }
          ]
        },
        "description_post": {
          "type": "array",
          "items": [
            {
              "type": "string"
            },
            {
              "type": "string"
            }
          ]
        }
      },
      "required": [
        "nature",
        "description",
        "description_post"
      ]
    },
    "goal": {
      "type": "array",
      "items": [
        {
          "type": "string"
        },
        {
          "type": "string"
        }
      ]
    },
    "settings": {
      "type": "object",
      "properties": {
        "place": {
          "type": "array",
          "items": [
            {
              "type": "string"
            },
            {
              "type": "string"
            },
            {
              "type": "string"
            },
            {
              "type": "string"
            }
          ]
        },
        "description": {
          "type": "array",
          "items": [
            {
              "type": "string"
            },
            {
              "type": "string"
            }
          ]
        }
      },
      "required": [
        "place",
        "description"
      ]
    },
    "theme": {
      "type": "array",
      "items": [
        {
          "type": "string"
        },
        {
          "type": "string"
        }
      ]
    },
    "mood": {
      "type": "array",
      "items": [
        {
          "type": "string"
        },
        {
          "type": "string"
        }
      ]
    },
    "wildcard": {
      "type": "array",
      "items": [
        {
          "type": "string"
        },
        {
          "type": "string"
        }
      ]
    }
  },
  "required": [
    "template",
    "genre",
    "genre_modifier",
    "perspective",
    "character",
    "goal",
    "settings",
    "theme",
    "mood",
    "wildcard"
  ]
}

=== myasinay/cs50-idea-generator/assets/docs/example_data.json
{
    "template": [
      "{mood} {perspective} {genre} game about {theme} and {themeAlternative}",
      "{mood} {perspective} {genre} game about {theme}, where you play as {character} {setting}",
      "{mood} {perspective} {genre} game {wildcard} where you play as {character} on a mission to {goal}",
      "{mood} {perspective} {genre} game that takes place {setting}, where you play as {character} on a mission to {goal}",
      "{mood} mashup of {perspective} {genre} and {genreAlternative} game genres, where you play as {character} on a mission to {goal}",
      "{mood} mix between {perspective} {genre} and {genreAlternative} game genres, which tells a story of {theme} and {themeAlternative}",
      "{mood} {perspective} {genre} game {wildcard}",
      "{mood} blend of {perspective} {genre} and {genreAlternative} game genres {wildcard}"
    ],
    "genre": [
      "platformer",
      "metroidvania",
      "endless",
      "runner",
      "shooter",
      "bullet",
      "hell",
      "sports",
      "strategy",
      "puzzle",
      "stealth",
      "role-playing",
      "roguelike",
      "dating",
      "survival",
      "horror",
      "card",
      "rhythm",
      "adventure",
      "tower-defense",
      "clicker",
      "hack-and-slash",
      "educational",
      "text-adventure",
      "typing",
      "sandbox",
      "programming",
      "boat racing",
      "car racing",
      "kart racing",
      "bike racing",
      "helicopter racing",
      "theme-park simulation",
      "business-management simulation",
      "city-management simulation",
      "farming simulation",
      "driving simulation",
      "flying simulation",
      "fishing",
      "football",
      "cricket",
      "basketball",
      "hockey",
      "tennis",
      "table",
      "tennis",
      "baseball",
      "golf",
      "volleyball",
      "fencing",
      "sword",
      "fighting",
      "horse",
      "riding",
      "snow",
      "boarding",
      "skiing",
      "skateboarding"
    ],
    "genre_modifier": [
      "open-world",
      "turn-based",
      "sci-fi",
      "fantasy",
      "realistic"
    ],
    "perspective": [
      "2D",
      "2.5D",
      "3D",
      "first-person",
      "third-person",
      "top-down",
      "isometric",
      "side-view"
    ],
    "character": {
      "nature": [
        "David J. Malan",
        "Doug Lloyd",
        "Brenda Anderson",
        "Glenn Holloway",
        "Rongxin Liu",
        "Brian Yu",
        "person"
      ],
      "description": [
        "gigantic",
        "time-travelling",
        "good-looking",
        "courageous",
        "famous",
        "ambitious",
        "power-hungry",
        "two-headed",
        "wise",
        "elderly",
        "invisible",
        "magical",
        "peace-loving",
        "polite",
        "genetically modified",
        "genetically enhanced",
        "charming",
        "energetic",
        "talkative",
        "royal",
        "wind-up",
        "law-breaking"
      ],
      "description_post": [
        "from another course",
        "who loves CS50",
        "who loves Harvard",
        "who loves Python",
        "who is passionate about CS50",
        "who is passionate about Harvard",
        "who is passionate about Python",
        "who is passionate about edX",
        "who loathes Yale",
        "who is addicted to CS50",
        "who is addicted to voil√†"
      ]
    },
    "goal": [
      "save the world from Yale",
      "fix bugs",
      "explore the Harvard",
      "learn programming",
      "start a new course",
      "escape from Yale",
      "rescue a friend from Yale"
    ],
    "settings": {
      "place": [
        "on a {description} moon",
        "on a {description} rainbow",
        "in a {description} school",
        "in an {description} office",
        "in an alternate reality",
        "in CS50",
        "in edX",
        "in autumn"
      ],
      "description": [
        "tiny",
        "microscopic",
        "royal"
      ]
    },
    "theme": [
      "survival",
      "cooking",
      "farming",
      "love",
      "death",
      "power",
      "prejudice",
      "hope",
      "war",
      "peace",
      "friendship",
      "revenge",
      "betrayal",
      "forgiveness",
      "crime",
      "punishment",
      "aliens",
      "isolation",
      "chaos",
      "the circle of life",
      "fate",
      "growing up",
      "immortality",
      "technology",
      "totalitarianism",
      "religion",
      "tradition",
      "mental",
      "illness",
      "space",
      "travel",
      "exploration",
      "greed",
      "justice",
      "patriotism",
      "corruption",
      "exploitation",
      "the end of the world",
      "unfairness",
      "hacking",
      "artificial",
      "intelligence",
      "the singularity",
      "robot rights",
      "extraterrestial life",
      "illness",
      "life after death",
      "dancing",
      "singing",
      "bee-keeping",
      "engineering",
      "sewing",
      "fashion",
      "baking",
      "stamp",
      "collecting",
      "art",
      "gardening",
      "happiness",
      "sadness",
      "the concept of fun",
      "chivalry",
      "stereotypes",
      "family",
      "relationships",
      "truth",
      "lies",
      "bravery",
      "cowardice",
      "mathematics"
    ],
    "mood": [
      "unique",
      "challenging",
      "innovative",
      "inspiring",
      "dreamy",
      "nostalgic"
    ],
    "wildcard": [
      "with a sad story",
      "with a scary story"
    ]
  }
